### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by mythodeia** [dkhamsing/apns-guide#2]
thanks for this guide. I have a quick question if thats ok with you, regarding APNS certificates.
I have an app with 10 test users which i deploy to using hockeyapp. 
The app uses APNS just fine. Now i have to add a new device ID (user).
I regenerated the provisioning profiles to add the new device.
Should i have revoked the APNS certificate as well before regenerating the provisioning profiles?
thanks for your time

**Comment by dkhamsing** [comment]
No, apns is tied to the app, not the users

**Comment by mythodeia** [comment]
Thanks!
