### ISSUE TITLE
question and error

### ISSUE THREAD

**Issue by siddo420** [dkhamsing/apns-guide#5]
Thanks for the detailed guide.

I followed every step (in fact copied and pasted commands) but I still get the error when I run test openssl command
```
verify error:num=20:unable to get local issuer certificate
```
I used Knuff and that seems to work fine  and sending notifications to my development app.

Also, I need the certificate and key to use for pushd which uses node-apn behind the scenes.

**Comment by dkhamsing** [comment]
@siddo420 did you resolve your issue

**Comment by siddo420** [comment]
Yes

**Comment by dkhamsing** [comment]
@siddo420 can you share some of your findings? thanks

**Comment by siddo420** [comment]
IIRC, I had to include the CA certificate (from Entrust).

**Comment by dkhamsing** [comment]
Thanks
