### ISSUE TITLE
Production Server Certificate

### ISSUE THREAD

**Issue by mariohmol** [dkhamsing/apns-guide#6]
Hi there!

I 'm receiving the ios token and i can send a push using development enviroment.

When i try to use the server, this gives me a error that i had before in dev (when I didnt had the Apple Push Notification service SSL Certificates for dev)

Well.. i have a linux server.. i created a CSR file. sent it production push certificate, it gave me a .cer file.

The thing is i tryed many ways to install this .cer in a linux server but i cant make it work.

What i did so far:

Create a CSR file : `openssl req -new -newkey rsa:2048 -nodes -keyout server.key -out server.csr`

Use this file in `https://developer.apple.com/account/ios/identifier/bundle/edit` to cerate the production certificate, and receive back a `aps.cer`

Then u used the command `openssl x509 -inform DER -in aps.cer -out certificate.crt` to converte from a .cer to a .crt file

I made a copy of the `crt` file into ` /etc/ssl/certs/`

Then tryed to install this cert in the server, `openssl x509 -noout -hash -in /etc/ssl/certs/certificate.crt`

But still having the issue, any ideas?

**Comment by dkhamsing** [comment]
no sorry
